version: "3.7"

services:
  blossom:
    image: ghcr.io/hzrd149/nostr-profile-cache:master
    build: .
    ports:
      - 3000:3000
    environment:
      DEBUG: "*"
      NOSTR_RELAYS: "wss://nostrue.com"
      NOSTR_NSEC: "<service nsec>"
